spring:
  application:
    name: ox-core-client
  
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:oxcoredb;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL}
    username: ${JDBC_DATABASE_USERNAME:SA}
    password: ${JDBC_DATABASE_PASSWORD:}
    driver-class-name: ${JDBC_DATABASE_DRIVER:org.h2.Driver}
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    clean-on-validation-error: true
    clean-disabled: false

  sql:
    init:
      mode: never

server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    com.ox.core.client: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.flywaydb: DEBUG

security:
  password:
    pattern: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\S+$).{8,}$
    max-attempts: 3
    lock-duration-minutes: 15
  jwt:
    secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: 86400000 # a day
    refresh-token:
      expiration: 604800000 # 7 days
