spring:
  application:
    name: ox-core-client
  
  datasource:
    url: jdbc:h2:mem:oxcoredb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: SA
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

server:
  port: 8080
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.ox.core.client: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:your-secret-key}
    expiration: ${JWT_EXPIRATION:86400}
  password:
    pattern: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\S+$).{8,}$
    max-attempts: 3
    lock-duration-minutes: 30
