spring:
  application:
    name: ox-core-client
  
  datasource:
    url: jdbc:h2:mem:oxcoredb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.ox.core.client: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

security:
  jwt:
    secret: your-256-bit-secret-key-here
    expiration: 86400000 # 24 hours in milliseconds
